//importing relevent modules
const express = require('express');
const router=express.Router();
require('dotenv').config();
const crypto=require('crypto');

//setting up environment variables
const accountSid=process.env.ACCOUNT_SID;//account secret key
const authToken=process.env.AUTH_TOKEN;//auth secret key
const client=require('twilio')(accountSid,authToken);//setting up sms api
const twilioNum = process.env.TWILIO_PHONE_NUMBER;//phoneno secret key
const jwt = require('jsonwebtoken');//json web token object
const JWT_AUTH_TOKEN=process.env.JWT_AUTH_TOKEN;//auth token secret key
const smsKey=process.env.SMS_SECRET_KEY;//sms secret key
const auth=require('../../middleware/auth');//middleware to verify the token
const User=require('../../models/User');//User model to save to db
const {check,validationResult}=require('express-validator');//express validator to check for errors


//@router get api/
//@desc get user object from db associated with the token
//@access public
router.get('/', auth, async (req, res) => {
	try {
		//get the details of the user from the db
	  const user = await User.findById(req.user.id);
	  //return the object in the form of JSON
	  res.json(user);
	} catch (error) {
	  //if error return status code
	  return res.status(400).json({ errors: [{msg:'server error'}] });
	}
  });

//@router POST api/sendOTP
//@desc Register user
//@access public
router.post('/sendOTP',check('userName','Name is required').not().isEmpty(),
check('phone','Phone No is required').not().isEmpty(),async(req, res) => {
	
	//errors object to store all errors generated by this api
	const errors=validationResult(req);
	if(!errors.isEmpty())
    {	//return all the errors in JSON format to the client
      return res.status(400).json({errors:errors.array()});
    }

	//destructuring the request object to get all the attributes
	const userName=req.body.userName;
	const phone = req.body.phone;

	//function to calculate otp
	const otp = Math.floor(100000 + Math.random() * 900000);
	const ttl = 2 * 60 * 1000;
	//get a expiry date
	const expires = Date.now() + ttl;

	//calculate hash to verify otp
	const data = `${phone}.${otp}.${expires}`;
	const hash = crypto.createHmac('sha256', smsKey).update(data).digest('hex');
	const fullHash = `${hash}.${expires}`;

	//sms message object 
	client.messages
		.create({
			body: `Your One Time Login Password For covid-assist is ${otp}`,
			from: twilioNum,
			to: phone
		})
		.then((messages) => console.log(messages))
		.catch((err) => console.error(err));

	//return the details in the form on JSON
	 res.status(200).send({ phone, hash: fullHash,otp,userName });          
});

//@router POST api/verifyOTP
//@desc verify otp recieved
//@access public
router.post('/verifyOTP', async(req, res) => {

	//destructuring the req object to populate all the attributes
	const userName=req.body.name;
	const phone = req.body.phone;
	const hash = req.body.hash;
	const otp = req.body.otp;

	//calculating the expiry date using hash
	let [ hashValue, expires ] = hash.split('.');

	//calculate todays date
	let now = Date.now();
	//check if otp is expired or not
	if (now > parseInt(expires)) {
		return res.status(400).json({ errors: [{msg:'Time Out Please Try again'}] });
	}
	//calculating new hash to verify otp
	let data = `${phone}.${otp}.${expires}`;
	let newCalculatedHash = crypto.createHmac('sha256', smsKey).update(data).digest('hex');
	//if calculated hash is equal to input hash valid otp
	if (newCalculatedHash === hashValue) {
		
		//check if user exists in db or not
		let user=await User.findOne({phone}) ;
		//if not register him in db
		if(!user){
			user=new User({
				userName,
				phone
			});
			//save data to db
			await user.save();
			
		}
		//create payload using user id
		const payload={
			user:{
				id:user.id
			}
		};

		
		//sign jwt token using user id
		 jwt.sign(payload, JWT_AUTH_TOKEN, { expiresIn: '60000s' },(err,token)=>{
			if(err) return res.status(400).json({ errors: [{msg:'incorrect Phone No'}] });
			//return token in the form of JSON
			res.json({token});
		});
			
	} else {
		//return if incorrect otp
		return res.status(400).json({ errors: [{msg:'incorrect OTP'}] });
	}
});


//export the module 
module.exports=router;
